version: '3.3'
services:
  pozos-registry:
    image: registry:2.8.1
    container_name: pozos-registry
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - /opt/docker/registry:/var/lib/registry
      - ./registry/auth:/auth
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    command:
      - /bin/sh
      - -c
      - 'apk add --no-cache apache2-utils && htpasswd -Bbn pozos change-me > /auth/htpasswd && registry serve /etc/docker/registry/config.yml'
    networks:
      - pozos_network

  frontend-reg:
    image: joxit/docker-registry-ui:2
    container_name: frontend-reg
    depends_on:
      - pozos-registry
    ports: 
      - "8090:80"
    environment:
      - NGINX_PROXY_PASS_URL=http://pozos-registry:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Pozos
      - SINGLE_REGISTRY=true
    networks:
      - pozos_network
  web:
    image: php:apache
    container_name: pozos_web
    depends_on:
      - api
    ports:
      - 80:80
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    
    networks:
      - pozos_network
  api:
    image: localhost:5000/pozos-api:0.1
    container_name: pozos_api
#    ports:
#      - 4000:5000
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    
    networks:
      - pozos_network
      
networks:
  pozos_network:
